language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8

sudo: false
addons:
  apt:
    packages:
    - graphviz

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

script:
- sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- sbt ++$TRAVIS_SCALA_VERSION mdocPublishDeb
deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: ogUMHPX0v9nsGZFJo0p1s8jpfY5Tgr6zFG7fSfhpKB5maA3qbjzZiRKA56kSKqj3DTJ7K55m6fJ0S5EvtQkRILmF/8lzuxijLL8FXpzZeY7+P/87zkEk4SuF0Z0oSGU6MKiy1YK/P1Vd0RRAMVaWxLoFt2WtyE6jRh4UqUsg1/Zb6tzDFYbLVc11NPaq002ipamzuuLhk3gmQn/RbEYJVHjfX/Ky3XbDBL/ycpW+ilg0NihxOB5MtBUtbiJMw2LYwjQGcf0+yqGzSNp8TJzXyKTfTQRXh+85KfUa+B35VoJ3lGcZVRZ4/MECH0w+LNr4+bNzqevKNAp1U/v8fM/jXTexWIewyyXPM4PPH2Ph28MdfY0M/YA7+0WkiDy2plikL5PLAcF6ijrF+jw4jydEB/grOMBgTp5UY7ZmBaNwQNFEhjqvk4taOCCcpJVKOsJWNXYUoWo6kk81v0710paw4zX8UG+HHyBLUQsaZ4x5jaSvgU+5BNqxMJHedbH7A7DfPHJOqOwRFrn8QPEB2OEsqQZaN9MfeNwTFBVEz4Rtc86AMJgHiUkUkXEib0dFJ0kgiGPtXQddPdGhLOR+K01eSLO7MrEmegcoNd91IaANwvcIGAWHTqNQYjPr7iWmVpLyuLKbiGL4tK9EYJQn/bzrlKOx7BVA9IAq9uzk0wh2U8g=
  key:
    secure: LPl1LkvtxE7wZxjPMGSZ5CXL29ec7pbLLTX4J03xgQGZxeQo9i97i8ozVg1DIg3cO05WsNoA57KhXx7cWTot1ageFhcANYMdR7vziVrNwOlEfwPIuH+0O2Qw1SWM+R+LB5vQL93gs/KmlTLtefUH5oIaQIvCgFWvEStxzlSdapd8l6OlN0nh3lft2W+P3UtZsnLzSRH741mJ7KagsYBXOIW6HG9/kxrDIaXK4CHUZhIZxYBa6CfQB+W5B1pjRyanlTal9VunppP0JJk3vtTT0kPnMdFzuvTkLiEydfbr80k43RG8aXUz7MgSZFa9jDbE6pz7jk5mT5sjOsNPEkRCeeSfBmIDMuCyDC2PSgZXuK8eMBpZUSQKmxNwzTW9oYqvYShRNjynC8AcxJc/gh942bbqtYwSfLG4BJ6hyhURs7SmKTo7+0SrQc3H+kMK1cwrCeVcUVw3daky1xoGfRzKNqqDkvQJqOgMsqtyd96elhKnlNxk2pmCk/eoyM9VK8EdHU1fF+yLhb/MuaV8yO/nuPMHaaPzXz4M4gQqBOEb68z/qOlA/U1C2pcGzMlx91ZKgON99mS+O/U/fms2P1zFhhoHsv3ZJbnpOYaCNGTCJYOEW/96TRPSfMveXOjltwpe8ceOyei/MJeLP4c0K5h2vH94M1QeLh+nz4DLWeWk+9Q=

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
